image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
  - cmd: msbuild /t:restore
  - cmd: msbuild /t:pack /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: 'MSBuild.Sdk.Extras.*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/xabluhq/api/v2/package
  api_key:
    secure: Ln3idOZxx941W5Hdj52B/FtCjABI78wXBFJrqKZ0i9oiVn0e30sq4AB+XFYys611gncTC9UKFVlpep06kXuJcIUYtfFl64aVG96L9+xHnMQ=
  artifact: /.*\.nupkg/